name: input_form
description: Customizable form with input fields.
version: 0.0.1
#homepage:
publish_to: 'none'
environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3
  wechat_assets_picker: ^7.3.2
  file_picker: ^4.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
